In [1]:
import numpy as np
import pandas as pd

In [6]:
col = ['id', 'Clump Thickness', 'Uniformity of Cell Size',
       'Uniformity of Cell Shape', 'Marginal Adhesion',
       'Single Epithelial Cell Size', 'Bare Nuclei', 'Bland Chromatin',
       'Normal Nucleoli', 'Mitoses', 'Class']


In [8]:
df = pd.read_csv("/content/drive/MyDrive/breast-cancer-wisconsin.data.csv", names = col, header = None)

In [9]:
df.head()

id  Clump Thickness  Uniformity of Cell Size  \
0  1000025                5                        1   
1  1002945                5                        4   
2  1015425                3                        1   
3  1016277                6                        8   
4  1017023                4                        1   

   Uniformity of Cell Shape  Marginal Adhesion  Single Epithelial Cell Size  \
0                         1                  1                            2   
1                         4                  5                            7   
2                         1                  1                            2   
3                         8                  1                            3   
4                         1                  3                            2   

  Bare Nuclei  Bland Chromatin  Normal Nucleoli  Mitoses  Class  
0           1                3                1        1      2  
1          10                3                2        1      2  
2           2                3                1        1      2  
3           4                3                7        1      2  
4           1                3                1        1      2

In [10]:
df.columns

Index(['id', 'Clump Thickness', 'Uniformity of Cell Size',
       'Uniformity of Cell Shape', 'Marginal Adhesion',
       'Single Epithelial Cell Size', 'Bare Nuclei', 'Bland Chromatin',
       'Normal Nucleoli', 'Mitoses', 'Class'],
      dtype='object')

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 699 entries, 0 to 698
Data columns (total 11 columns):
 #   Column                       Non-Null Count  Dtype 
---  ------                       --------------  ----- 
 0   id                           699 non-null    int64 
 1   Clump Thickness              699 non-null    int64 
 2   Uniformity of Cell Size      699 non-null    int64 
 3   Uniformity of Cell Shape     699 non-null    int64 
 4   Marginal Adhesion            699 non-null    int64 
 5   Single Epithelial Cell Size  699 non-null    int64 
 6   Bare Nuclei                  699 non-null    object
 7   Bland Chromatin              699 non-null    int64 
 8   Normal Nucleoli              699 non-null    int64 
 9   Mitoses                      699 non-null    int64 
 10  Class                        699 non-null    int64 
dtypes: int64(10), object(1)
memory usage: 60.2+ KB


In [13]:
np.where(df.isnull())

(array([], dtype=int64), array([], dtype=int64))

In [14]:
df["Bare Nuclei"].describe()

count     699
unique     11
top         1
freq      402
Name: Bare Nuclei, dtype: object

In [15]:
df["Bare Nuclei"].value_counts()

Bare Nuclei
1     402
10    132
2      30
5      30
3      28
8      21
4      19
?      16
9       9
7       8
6       4
Name: count, dtype: int64

In [17]:
df[df["Bare Nuclei"] == "?"]

id  Clump Thickness  Uniformity of Cell Size  \
23   1057013                8                        4   
40   1096800                6                        6   
139  1183246                1                        1   
145  1184840                1                        1   
158  1193683                1                        1   
164  1197510                5                        1   
235  1241232                3                        1   
249   169356                3                        1   
275   432809                3                        1   
292   563649                8                        8   
294   606140                1                        1   
297    61634                5                        4   
315   704168                4                        6   
321   733639                3                        1   
411  1238464                1                        1   
617  1057067                1                        1   

     Uniformity of Cell Shape  Marginal Adhesion  Single Epithelial Cell Size  \
23                          5                  1                            2   
40                          6                  9                            6   
139                         1                  1                            1   
145                         3                  1                            2   
158                         2                  1                            3   
164                         1                  1                            2   
235                         4                  1                            2   
249                         1                  1                            2   
275                         3                  1                            2   
292                         8                  1                            2   
294                         1                  1                            2   
297                         3                  1                            2   
315                         5                  6                            7   
321                         1                  1                            2   
411                         1                  1                            1   
617                         1                  1                            1   

    Bare Nuclei  Bland Chromatin  Normal Nucleoli  Mitoses  ...  10  2  4  3  \
23            ?                7                3        1  ...   ?  ?  ?  ?   
40            ?                7                8        1  ...   ?  ?  ?  ?   
139           ?                2                1        1  ...   ?  ?  ?  ?   
145           ?                2                1        1  ...   ?  ?  ?  ?   
158           ?                1                1        1  ...   ?  ?  ?  ?   
164           ?                3                1        1  ...   ?  ?  ?  ?   
235           ?                3                1        1  ...   ?  ?  ?  ?   
249           ?                3                1        1  ...   ?  ?  ?  ?   
275           ?                2                1        1  ...   ?  ?  ?  ?   
292           ?                6               10        1  ...   ?  ?  ?  ?   
294           ?                2                1        1  ...   ?  ?  ?  ?   
297           ?                2                3        1  ...   ?  ?  ?  ?   
315           ?                4                9        1  ...   ?  ?  ?  ?   
321           ?                3                1        1  ...   ?  ?  ?  ?   
411           ?                2                1        1  ...   ?  ?  ?  ?   
617           ?                1                1        1  ...   ?  ?  ?  ?   

     9  7  ?  5  8  6  
23   ?  ?  ?  ?  ?  ?  
40   ?  ?  ?  ?  ?  ?  
139  ?  ?  ?  ?  ?  ?  
145  ?  ?  ?  ?  ?  ?  
158  ?  ?  ?  ?  ?  ?  
164  ?  ?  ?  ?  ?  ?  
235  ?  ?  ?  ?  ?  ?  
249  ?  ?  ?  ?  ?  ?  
275  ?  ?  ?  ?  ?  ?  
292  ?  ?  ?  ?  ?  ?  
294  ?  ?  ?  ?  ?  

In [18]:
df["Bare Nuclei"].replace("?", np.NAN, inplace = True)
df.dropna(inplace = True)

<ipython-input-18-30a2e82db35f>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Bare Nuclei"].replace("?", np.NAN, inplace = True)


In [20]:
df["Bare Nuclei"].value_counts()

Bare Nuclei
1     402
10    132
2      30
5      30
3      28
8      21
4      19
9       9
7       8
6       4
Name: count, dtype: int64

In [21]:
df["Class"].value_counts()

Class
2    444
4    239
Name: count, dtype: int64

In [22]:
df["Class"] = df["Class"]/2 - 1
df["Class"]

0      0.0
1      0.0
2      0.0
3      0.0
4      0.0
      ... 
694    0.0
695    0.0
696    1.0
697    1.0
698    1.0
Name: Class, Length: 683, dtype: float64

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 683 entries, 0 to 698
Data columns (total 22 columns):
 #   Column                       Non-Null Count  Dtype  
---  ------                       --------------  -----  
 0   id                           683 non-null    int64  
 1   Clump Thickness              683 non-null    int64  
 2   Uniformity of Cell Size      683 non-null    int64  
 3   Uniformity of Cell Shape     683 non-null    int64  
 4   Marginal Adhesion            683 non-null    int64  
 5   Single Epithelial Cell Size  683 non-null    int64  
 6   Bare Nuclei                  683 non-null    object 
 7   Bland Chromatin              683 non-null    int64  
 8   Normal Nucleoli              683 non-null    int64  
 9   Mitoses                      683 non-null    int64  
 10  Class                        683 non-null    float64
 11  1                            683 non-null    object 
 12  10                           683 non-null    object 
 13  2                        

In [24]:
df.shape

(683, 22)

In [32]:
df.columns

Index(['id', 'Clump Thickness', 'Uniformity of Cell Size',
       'Uniformity of Cell Shape', 'Marginal Adhesion',
       'Single Epithelial Cell Size', 'Bare Nuclei', 'Bland Chromatin',
       'Normal Nucleoli', 'Mitoses', 'Class', '1', '10', '2', '4', '3', '9',
       '7', '?', '5', '8', '6'],
      dtype='object')

In [33]:
df = df[['id', 'Clump Thickness', 'Uniformity of Cell Size',
       'Uniformity of Cell Shape', 'Marginal Adhesion',
       'Single Epithelial Cell Size', 'Bare Nuclei', 'Bland Chromatin',
       'Normal Nucleoli', 'Mitoses', 'Class']]

In [34]:
y = df["Class"]
X = df.drop(["id", "Class"], axis = 1)
X_col = X.columns
X_col

Index(['Clump Thickness', 'Uniformity of Cell Size',
       'Uniformity of Cell Shape', 'Marginal Adhesion',
       'Single Epithelial Cell Size', 'Bare Nuclei', 'Bland Chromatin',
       'Normal Nucleoli', 'Mitoses'],
      dtype='object')

In [36]:
from sklearn.preprocessing import StandardScaler
X = StandardScaler().fit_transform(X.values)

In [37]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

In [39]:
from sklearn.preprocessing import MinMaxScaler
X = MinMaxScaler().fit_transform(X)
X

array([[0.44444444, 0.        , 0.        , ..., 0.22222222, 0.        ,
        0.        ],
       [0.44444444, 0.33333333, 0.33333333, ..., 0.22222222, 0.11111111,
        0.        ],
       [0.22222222, 0.        , 0.        , ..., 0.22222222, 0.        ,
        0.        ],
       ...,
       [0.44444444, 1.        , 1.        , ..., 0.77777778, 1.        ,
        0.11111111],
       [0.33333333, 0.77777778, 0.55555556, ..., 1.        , 0.55555556,
        0.        ],
       [0.33333333, 0.77777778, 0.77777778, ..., 1.        , 0.33333333,
        0.        ]])

In [40]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors = 5, p = 2, metric = "minkowski")
knn.fit(X, y)

KNeighborsClassifier()

In [42]:
from sklearn.model_selection import cross_val_predict, cross_val_score
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [46]:
res = cross_val_score(knn, X, y, cv = 10, scoring = "accuracy")
res

array([0.91304348, 0.98550725, 0.95652174, 0.94117647, 1.        ,
       0.97058824, 0.98529412, 1.        , 0.98529412, 0.97058824])

In [43]:
def print_score(clf, X_train, y_train, X_test, y_test, train=True):
    if train:
        print("Train Result:\n")
        print("accuracy score: {0:.4f}\n".format(accuracy_score(y_train, clf.predict(X_train))))
        print("Classification Report: \n {}\n".format(classification_report(y_train, clf.predict(X_train))))
        print("Confusion Matrix: \n {}\n".format(confusion_matrix(y_train, clf.predict(X_train))))

        res = cross_val_score(clf, X_train, y_train, cv=10, scoring='accuracy')
        print("Average Accuracy: \t {0:.4f}".format(np.mean(res)))
        print("Accuracy SD: \t\t {0:.4f}".format(np.std(res)))

    elif train==False:
        print("Test Result:\n")
        print("accuracy score: {0:.4f}\n".format(accuracy_score(y_test, clf.predict(X_test))))
        print("Classification Report: \n {}\n".format(classification_report(y_test, clf.predict(X_test))))
        print("Confusion Matrix: \n {}\n".format(confusion_matrix(y_test, clf.predict(X_test))))

In [49]:
y.shape

(683,)

In [50]:
X.shape

(683, 9)

In [61]:
print("with KNN")
print_score(knn, X_train, y_train, X_test, y_test, train = True)

with KNN
Train Result:

accuracy score: 0.9762

Classification Report: 
               precision    recall  f1-score   support

         0.0       0.98      0.98      0.98       365
         1.0       0.96      0.97      0.96       181

    accuracy                           0.98       546
   macro avg       0.97      0.97      0.97       546
weighted avg       0.98      0.98      0.98       546


Confusion Matrix: 
 [[358   7]
 [  6 175]]

Average Accuracy: 	 0.9634
Accuracy SD: 		 0.0200


#GridSearch

In [62]:
from sklearn.model_selection import GridSearchCV

In [63]:
knn.get_params

<bound method BaseEstimator.get_params of KNeighborsClassifier()>

In [64]:
params = {"n_neighbors" : [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]}

In [65]:
grid_search_cv = GridSearchCV(KNeighborsClassifier(), params, n_jobs = -1, verbose = 1)
grid_search_cv

GridSearchCV(estimator=KNeighborsClassifier(), n_jobs=-1,
             param_grid={'n_neighbors': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]},
             verbose=1)

In [66]:
grid_search_cv.fit(X_train, y_train)

Fitting 5 folds for each of 10 candidates, totalling 50 fits


GridSearchCV(estimator=KNeighborsClassifier(), n_jobs=-1,
             param_grid={'n_neighbors': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]},
             verbose=1)

In [67]:
grid_search_cv.best_estimator_

KNeighborsClassifier(n_neighbors=8)

In [68]:
print("with GridSearchCV")
print_score(grid_search_cv, X_train, y_train, X_test, y_test, train = True)

with GridSearchCV
Train Result:

accuracy score: 0.9707

Classification Report: 
               precision    recall  f1-score   support

         0.0       0.98      0.98      0.98       365
         1.0       0.96      0.95      0.96       181

    accuracy                           0.97       546
   macro avg       0.97      0.97      0.97       546
weighted avg       0.97      0.97      0.97       546


Confusion Matrix: 
 [[358   7]
 [  9 172]]

Fitting 5 folds for each of 10 candidates, totalling 50 fits
Fitting 5 folds for each of 10 candidates, totalling 50 fits
Fitting 5 folds for each of 10 candidates, totalling 50 fits
Fitting 5 folds for each of 10 candidates, totalling 50 fits
Fitting 5 folds for each of 10 candidates, totalling 50 fits
Fitting 5 folds for each of 10 candidates, totalling 50 fits
Fitting 5 folds for each of 10 candidates, totalling 50 fits
Fitting 5 folds for each of 10 candidates, totalling 50 fits
Fitting 5 folds for each of 10 candidates, totalling 50 fi

In [69]:
grid_search_cv.cv_results_

{'mean_fit_time': array([0.00267172, 0.00247612, 0.00251613, 0.00248618, 0.0031014 ,
        0.00243635, 0.00245743, 0.00246792, 0.00281219, 0.00256629]),
 'std_fit_time': array([2.27255257e-04, 9.90789822e-05, 1.21641953e-04, 1.39163714e-04,
        7.46630663e-04, 4.11625102e-05, 1.95276687e-04, 5.64167884e-05,
        7.38227061e-04, 1.84385869e-04]),
 'mean_score_time': array([0.01399331, 0.01417584, 0.01402826, 0.01426048, 0.01507406,
        0.01497283, 0.01558657, 0.01381121, 0.01741176, 0.01403975]),
 'std_score_time': array([0.00111736, 0.00098445, 0.00110181, 0.00189655, 0.00104623,
        0.00165967, 0.0040315 , 0.00034999, 0.00413181, 0.00211181]),
 'param_n_neighbors': masked_array(data=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
              mask=[False, False, False, False, False, False, False, False,
                    False, False],
        fill_value=999999),
 'params': [{'n_neighbors': 1},
  {'n_neighbors': 2},
  {'n_neighbors': 3},
  {'n_neighbors': 4},
  {'n_neighbors': 5}